# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-25 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.IntegerField()),
                ('reservation_representation', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField()),
                ('action', models.CharField(choices=[(b'add', b'Add'), (b'delete', b'Delete'), (b'modify', b'Modify')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(choices=[(b'#ff99ff', b'pink'), (b'#ff9999', b'salmon'), (b'#ff9933', b'orange'), (b'#cc9933', b'mustard'), (b'#cccc99', b'tan'), (b'#ccff33', b'yellow'), (b'#99ff00', b'limegreen'), (b'#00ff66', b'green'), (b'#00ccff', b'blue'), (b'#9999ff', b'purple'), (b'#999999', b'grey'), (b'#999966', b'greengrey')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCaReM.Camp')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(to='SCaReM.Tag'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='resources',
            field=models.ManyToManyField(to='SCaReM.Resource'),
        ),
    ]
