# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCaReM', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resources',
            new_name='Resource',
        ),
        migrations.RenameModel(
            old_name='ResourceTags',
            new_name='ResourceTag',
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
