# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCaReM', '0002_auto_20160709_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
