# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-31 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCaReM', '0003_reservation_recurrence_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='repeat_until',
        ),
    ]
