# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCaReM', '0005_auto_20160709_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcetag',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='resourcetag',
            name='tag',
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(to='SCaReM.Tag'),
        ),
        migrations.DeleteModel(
            name='ResourceTag',
        ),
    ]
